if: branch =~ ^master$|^development$|^release|^uat
language: python2.7
group: stable
dist: trusty
os: linux
sudo: required
services:
- docker
cache: pip

before_install: |-
  set -e
  sudo apt-get  -y   install python2.7
  sudo python2  --version
  if [ "master" == "${TRAVIS_BRANCH}" ]; then
    for env_value in $(compgen -v |grep '.*_PRODUCTION$'); do
      eval export ${env_value%_PRODUCTION}="${!env_value}"
    done
    export ENVIRONMENT=production
  elif [[ "${TRAVIS_BRANCH}" == release*  ]]; then
    for env_value in $(compgen -v |grep '.*_STAGING$'); do
      eval export ${env_value%_STAGING}="${!env_value}"
    done
    export ENVIRONMENT=staging
  else
    for env_value in $(compgen -v |grep '.*_DEVELOPMENT$'); do
      eval export ${env_value%_DEVELOPMENT}="${!env_value}"
    done
    export ENVIRONMENT=development
  fi

install:
  apt-get  -y   install python2.7 && python --version  && python2 --version  && python2.7 --version
