if: branch =~ ^master$|^development$|^release|^uat
language: python
  - python: 2.7
group: stable
dist: trusty
os: linux
sudo: required
services:
- docker
cache: pip


install:
   sudo echo "python test" && sudo ls -a /usr/bin/ 


